language: php

php:
  - 5.3

before_script:
  - travis_retry composer update

script:
  # check coding standard for our code
  - vendor/bin/phpcs -p --standard=psr2 src tests
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  # get scrutinizer for coverage upload
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
